
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

const envPath = path.join(process.cwd(), '.env');
const envContent = fs.readFileSync(envPath, 'utf8');
const env: Record<string, string> = {};
envContent.split('\n').forEach(line => {
  const [key, ...values] = line.split('=');
  if (key && values.length > 0) {
    env[key.trim()] = values.join('=').trim().replace(/['"]/g, '');
  }
});

const supabase = createClient(
  env['VITE_SUPABASE_URL'] || 'http://127.0.0.1:54321', 
  env['SUPABASE_SERVICE_ROLE_KEY'] || env['VITE_SUPABASE_ANON_KEY'] || 'dummy'
);

const missingDnas = [
  {
    "kode_surat": "475.0",
    "field_name": "alamat_tujuan",
    "label": "Alamat Tujuan",
    "tipe": "textarea",
    "placeholder": "Jl. ... RT/RW ...",
    "wajib": true,
    "grup": "Tujuan",
    "urutan": 1,
    "help_text": "Alamat lengkap tujuan pindah)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "rt_tujuan",
    "label": "RT Tujuan",
    "tipe": "text",
    "placeholder": "001",
    "wajib": true,
    "grup": "Tujuan",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "rw_tujuan",
    "label": "RW Tujuan",
    "tipe": "text",
    "placeholder": "001",
    "wajib": true,
    "grup": "Tujuan",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "kab_kota_tujuan",
    "label": "Kabupaten/Kota Tujuan",
    "tipe": "text",
    "placeholder": "Kabupaten Lombok Timur",
    "wajib": true,
    "grup": "Tujuan",
    "urutan": 4,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "kec_tujuan",
    "label": "Kecamatan Tujuan",
    "tipe": "text",
    "placeholder": "Kecamatan Pringgabaya",
    "wajib": true,
    "grup": "Tujuan",
    "urutan": 5,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "desa_tujuan",
    "label": "Desa/Kelurahan Tujuan",
    "tipe": "text",
    "placeholder": "Desa ...",
    "wajib": true,
    "grup": "Tujuan",
    "urutan": 6,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "alasan_pindah",
    "label": "Alasan Pindah",
    "tipe": "textarea",
    "placeholder": "Alasan ...",
    "wajib": true,
    "grup": "Pindah",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "anggota_pindah",
    "label": "Daftar Anggota Pindah",
    "tipe": "textarea",
    "placeholder": "1. Nama - NIK - Hubungan%n2. ...",
    "wajib": false,
    "grup": "Pindah",
    "urutan": 11,
    "help_text": "Daftar anggota keluarga yang ikut pindah)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "no_surat_pindah_lama",
    "label": "No. Surat Pindah Lama",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Pindah",
    "urutan": 12,
    "help_text": "Jika ada surat pindah sebelumnya"
  },
  {
    "kode_surat": "510.0",
    "field_name": "nama_usaha",
    "label": "Nama Usaha",
    "tipe": "text",
    "placeholder": "Warung Seruni",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 1,
    "help_text": "Nama dagang / usaha"
  },
  {
    "kode_surat": "510.0",
    "field_name": "jenis_bidang",
    "label": "Jenis Bidang Usaha",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 2,
    "help_text": "Sektor usaha"
  },
  {
    "kode_surat": "510.0",
    "field_name": "komoditas",
    "label": "Komoditas / Produk Utama",
    "tipe": "text",
    "placeholder": "Makanan, Minuman, Sembako",
    "wajib": false,
    "grup": "Usaha",
    "urutan": 3,
    "help_text": null
  },
  {
    "kode_surat": "510.0",
    "field_name": "alamat_usaha",
    "label": "Alamat Usaha",
    "tipe": "textarea",
    "placeholder": "Jl. ... RT/RW ...",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 4,
    "help_text": "Lokasi usaha lengkap"
  },
  {
    "kode_surat": "510.0",
    "field_name": "rt_usaha",
    "label": "RT",
    "tipe": "text",
    "placeholder": "001",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 5,
    "help_text": null
  },
  {
    "kode_surat": "510.0",
    "field_name": "rw_usaha",
    "label": "RW",
    "tipe": "text",
    "placeholder": "001",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 6,
    "help_text": null
  },
  {
    "kode_surat": "510.0",
    "field_name": "berdiri_sejak",
    "label": "Berdiri Sejak",
    "tipe": "date",
    "placeholder": "",
    "wajib": false,
    "grup": "Usaha",
    "urutan": 7,
    "help_text": "Tanggal mulai usaha"
  },
  {
    "kode_surat": "510.0",
    "field_name": "jumlah_karyawan",
    "label": "Jumlah Karyawan",
    "tipe": "number",
    "placeholder": "0",
    "wajib": false,
    "grup": "Usaha",
    "urutan": 8,
    "help_text": "Jumlah tenaga kerja"
  },
  {
    "kode_surat": "510.0",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "Untuk pengajuan kredit / tender / dll",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 10,
    "help_text": null
  },
  {
    "kode_surat": "477.4",
    "field_name": "nik_almarhum",
    "label": "NIK Almarhum/Almarhumah",
    "tipe": "text",
    "placeholder": "5201010101010001",
    "wajib": true,
    "grup": "Data",
    "urutan": 1,
    "help_text": "Nomor NIK yang tertera di KTP)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "nama_almarhum",
    "label": "Nama Lengkap",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "tanggal_meninggal",
    "label": "Tanggal Meninggal",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Kematian",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "hari_meninggal",
    "label": "Hari Meninggal",
    "tipe": "text",
    "placeholder": "Senin/Selasa/...",
    "wajib": true,
    "grup": "Kematian",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "pukul_meninggal",
    "label": "Pukul (Waktu)",
    "tipe": "text",
    "placeholder": "14.00 WITA",
    "wajib": false,
    "grup": "Kematian",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "sebab_meninggal",
    "label": "Sebab Meninggal",
    "tipe": "textarea",
    "placeholder": "Sakit tua/ Kecelakaan/ Lainnya",
    "wajib": true,
    "grup": "Kematian",
    "urutan": 13,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "tempat_meninggal",
    "label": "Tempat Meninggal",
    "tipe": "text",
    "placeholder": "Rumah Sakit/ Rumah/ Lainnya",
    "wajib": true,
    "grup": "Kematian",
    "urutan": 14,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "tempat_pemakaman",
    "label": "Tempat Pemakaman",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Kematian",
    "urutan": 15,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "no_akta_kematian",
    "label": "No. Akta Kematian",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Kematian",
    "urutan": 16,
    "help_text": "Diisi setelah ada akta kematian dari Dukcapil)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "yang_melaporkan",
    "label": "Yang Melaporkan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pelapor",
    "urutan": 20,
    "help_text": "Nama pelapor)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "hub_pelapor",
    "label": "Hubungan dengan Almarhum",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pelapor",
    "urutan": 21,
    "help_text": "Contoh: Anak, Istri, Suami, etc"
  },
  {
    "kode_surat": "477.3",
    "field_name": "nama_bayi",
    "label": "Nama Bayi",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Bayi",
    "urutan": 1,
    "help_text": "Kosongkan jika belum diberi nama"
  },
  {
    "kode_surat": "477.3",
    "field_name": "jenis_kelamin_bayi",
    "label": "Jenis Kelamin",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Bayi",
    "urutan": 2,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "anak_ke",
    "label": "Anak ke-",
    "tipe": "number",
    "placeholder": "1",
    "wajib": true,
    "grup": "Bayi",
    "urutan": 3,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "tanggal_lahir",
    "label": "Tanggal Lahir",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Bayi",
    "urutan": 10,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "pukul_lahir",
    "label": "Pukul (Waktu)",
    "tipe": "text",
    "placeholder": "10.00 WITA",
    "wajib": false,
    "grup": "Bayi",
    "urutan": 11,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "tempat_lahir",
    "label": "Tempat Lahir",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Bayi",
    "urutan": 12,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "no_akta_lahir",
    "label": "No. Akta Lahir (jika ada)",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Bayi",
    "urutan": 13,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "nik_ayah",
    "label": "NIK Ayah",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "nama_ayah",
    "label": "Nama Ayah",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 21,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "nik_ibu",
    "label": "NIK Ibu",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 22,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "nama_ibu",
    "label": "Nama Ibu",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 23,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "pelapor",
    "label": "Yang Melaporkan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pelapor",
    "urutan": 30,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "hub_pelapor",
    "label": "Hubungan dengan Bayi",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pelapor",
    "urutan": 31,
    "help_text": "Contoh: Ayah, Ibu, Kakek, etc"
  },
  {
    "kode_surat": "465.0",
    "field_name": "penghasilan_per_bulan",
    "label": "Penghasilan per Bulan",
    "tipe": "number",
    "placeholder": "500000",
    "wajib": true,
    "grup": "Ekonomi",
    "urutan": 1,
    "help_text": "Penghasilan kotor per bulan (Rp)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "jumlah_tanggungan",
    "label": "Jumlah Tanggungan",
    "tipe": "number",
    "placeholder": "4",
    "wajib": true,
    "grup": "Ekonomi",
    "urutan": 2,
    "help_text": "Jumlah anggota keluarga yang ditanggung"
  },
  {
    "kode_surat": "465.0",
    "field_name": "kondisi_tempat_tinggal",
    "label": "Kondisi Tempat Tinggal",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Ekonomi",
    "urutan": 3,
    "help_text": null
  },
  {
    "kode_surat": "465.0",
    "field_name": "sumber_penghasilan",
    "label": "Sumber Penghasilan",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Ekonomi",
    "urutan": 4,
    "help_text": null
  },
  {
    "kode_surat": "465.0",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "Untuk biaya pendidikan/berobat/bantuan",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 10,
    "help_text": null
  },
  {
    "kode_surat": "474.6",
    "field_name": "barang_hilang",
    "label": "Barang/Dokumen yang Hilang",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "no_dokumen",
    "label": "Nomor Dokumen",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Kehilangan",
    "urutan": 2,
    "help_text": "No. KTP/SIM/dokumen yang hilang)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "tanggal_hilang",
    "label": "Tanggal Perkiraan Hilang",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "lokasi_hilang",
    "label": "Lokasi Hilang",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "kronologi",
    "label": "Kronologi Kejadian",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 12,
    "help_text": null
  },
  {
    "kode_surat": "474.7",
    "field_name": "nama_ayah",
    "label": "Nama Ayah Kandung",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "nik_ayah",
    "label": "NIK Ayah",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Orang Tua",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "pekerjaan_ayah",
    "label": "Pekerjaan Ayah",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Orang Tua",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "alamat_ayah",
    "label": "Alamat Ayah",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": false,
    "grup": "Orang Tua",
    "urutan": 4,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "nama_ibu",
    "label": "Nama Ibu Kandung",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 5,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "nik_ibu",
    "label": "NIK Ibu",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Orang Tua",
    "urutan": 6,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "pekerjaan_ibu",
    "label": "Pekerjaan Ibu",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Orang Tua",
    "urutan": 7,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "alamat_ibu",
    "label": "Alamat Ibu",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": false,
    "grup": "Orang Tua",
    "urutan": 8,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 10,
    "help_text": null
  },
  {
    "kode_surat": "474.9",
    "field_name": "nama_pewaris",
    "label": "Nama Pewaris (Almarhum)",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pewaris",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "nik_pewaris",
    "label": "NIK Pewaris",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pewaris",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "tanggal_meninggal_pewaris",
    "label": "Tanggal Meninggal",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Pewaris",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "tempat_meninggal_pewaris",
    "label": "Tempat Meninggal",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pewaris",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "no_akta_kematian_pewaris",
    "label": "No. Akta Kematian",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Pewaris",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "daftar_ahli_waris",
    "label": "Daftar Ahli Waris",
    "tipe": "textarea",
    "placeholder": "1. Nama - NIK - Hubungan%n2. ...",
    "wajib": true,
    "grup": "Ahli Waris",
    "urutan": 20,
    "help_text": "Sesuai urutan hukum waris)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 30,
    "help_text": null
  },
  {
    "kode_surat": "474.3",
    "field_name": "nama_di_ktp",
    "label": "Nama di KTP",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Dokumen",
    "urutan": 1,
    "help_text": "Nama resmi di KTP/KK)"
  },
  {
    "kode_surat": "474.3",
    "field_name": "nama_di_dokumen_lain",
    "label": "Nama di Dokumen Lain",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Dokumen",
    "urutan": 2,
    "help_text": "Nama yang tertulis berbeda)"
  },
  {
    "kode_surat": "474.3",
    "field_name": "jenis_dokumen",
    "label": "Jenis Dokumen",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Dokumen",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.3",
    "field_name": "penyebab",
    "label": "Penyebab Perbedaan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Dokumen",
    "urutan": 4,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.3",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 10,
    "help_text": null
  },
  {
    "kode_surat": "451.0",
    "field_name": "nik_suami",
    "label": "NIK Calon Suami",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Suami",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "nama_suami",
    "label": "Nama Calon Suami",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Suami",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "ttl_suami",
    "label": "TTL Calon Suami",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Suami",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "status_suami",
    "label": "Status Pernikahan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Suami",
    "urutan": 4,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "nama_ayah_suami",
    "label": "Nama Ayah Suami",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Suami",
    "urutan": 5,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "nama_ibu_suami",
    "label": "Nama Ibu Suami",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Suami",
    "urutan": 6,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "nik_istri",
    "label": "NIK Calon Istri",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Istri",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "nama_istri",
    "label": "Nama Calon Istri",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Istri",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "ttl_istri",
    "label": "TTL Calon Istri",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Istri",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "status_istri",
    "label": "Status Pernikahan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Istri",
    "urutan": 13,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "nama_ayah_istri",
    "label": "Nama Ayah Istri",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Istri",
    "urutan": 14,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "nama_ibu_istri",
    "label": "Nama Ibu Istri",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data Istri",
    "urutan": 15,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "nama_wali",
    "label": "Nama Wali Nikah",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Wali",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "hubungan_wali",
    "label": "Hubungan Wali",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Wali",
    "urutan": 21,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "tanggal_akad",
    "label": "Tanggal Rencana Akad",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Nikah",
    "urutan": 30,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "tempat_akad",
    "label": "Tempat Akad",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Nikah",
    "urutan": 31,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "kua_tujuan",
    "label": "KUA Kecamatan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Nikah",
    "urutan": 32,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "seri_formulir",
    "label": "Seri Formulir",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Nikah",
    "urutan": 33,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.0",
    "field_name": "no_akta_cerai",
    "label": "No. Akta Cerai (jika ada)",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Nikah",
    "urutan": 34,
    "help_text": null
  },
  {
    "kode_surat": "477.1",
    "field_name": "nama_mantan",
    "label": "Nama Suami/Mantan Suami",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Data",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.1",
    "field_name": "nik_mantan",
    "label": "NIK Mantan Pasangan",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Data",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.1",
    "field_name": "penyebab",
    "label": "Penyebab Status",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Data",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.1",
    "field_name": "no_akta_cerai",
    "label": "No. Akta Cerai/Putusan PA",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Data",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.1",
    "field_name": "tanggal_cerai",
    "label": "Tanggal Cerai/Meninggal",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Data",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.1",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "474.9",
    "field_name": "nama_pewaris",
    "label": "Nama Pewaris",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pewaris",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "ttl_pewaris",
    "label": "TTL Pewaris",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pewaris",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "tanggal_meninggal",
    "label": "Tanggal Meninggal",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Pewaris",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "tempat_meninggal",
    "label": "Tempat Meninggal",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pewaris",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "no_akta_kematian",
    "label": "No. Akta Kematian",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Pewaris",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "harta_aset",
    "label": "Harta/Aset Pokok",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Ahli Waris",
    "urutan": 20,
    "help_text": "Aset yang diwariskan)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "jumlah_ahli_waris",
    "label": "Jumlah Total Ahli Waris",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Ahli Waris",
    "urutan": 21,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "pernyataan_tidak_ada",
    "label": "Pernyataan Tidak Ada Ahli Waris Lain",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Ahli Waris",
    "urutan": 22,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.9",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 30,
    "help_text": null
  },
  {
    "kode_surat": "140.0",
    "field_name": "nama_penyelenggara",
    "label": "Nama Penyelenggara/PIC",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Penyelenggara",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "nik_penyelenggara",
    "label": "NIK Penyelenggara",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Penyelenggara",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "nama_organisasi",
    "label": "Nama Organisasi (jika ada)",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Penyelenggara",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "jenis_acara",
    "label": "Jenis/Nama Acara",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Acara",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "tanggal_pelaksanaan",
    "label": "Tanggal Pelaksanaan",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Acara",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "jam_mulai",
    "label": "Jam Mulai",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Acara",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "jam_selesai",
    "label": "Jam Selesai",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Acara",
    "urutan": 13,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "tempat_acara",
    "label": "Tempat/Lokasi",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Acara",
    "urutan": 14,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "jumlah_peserta",
    "label": "Perkiraan Jumlah Peserta",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Acara",
    "urutan": 15,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "sound_system",
    "label": "Menggunakan Sound System",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Acara",
    "urutan": 16,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.0",
    "field_name": "petugas_keamanan",
    "label": "Petugas Keamanan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Acara",
    "urutan": 17,
    "help_text": null
  },
  {
    "kode_surat": "30.1",
    "field_name": "lokasi_tanah",
    "label": "Lokasi/Alamat Tanah",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Tanah",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "luas_tanah",
    "label": "Luas Tanah (m2)",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Tanah",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "no_persil",
    "label": "Nomor Persil/Blok",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Tanah",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "kelas_tanah",
    "label": "Kelas/Jenis Tanah",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Tanah",
    "urutan": 4,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "batas_utara",
    "label": "Batas Utara",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Batas",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "batas_selatan",
    "label": "Batas Selatan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Batas",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "batas_timur",
    "label": "Batas Timur",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Batas",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "batas_barat",
    "label": "Batas Barat",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Batas",
    "urutan": 13,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "status_kepemilikan",
    "label": "Status/Dasar Kepemilikan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Kepemilikan",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "no_sppt",
    "label": "Nomor SPPT PBB",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Kepemilikan",
    "urutan": 21,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "peruntukan",
    "label": "Penggunaan/Peruntukan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Kepemilikan",
    "urutan": 22,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.1",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 30,
    "help_text": null
  },
  {
    "kode_surat": "30.9",
    "field_name": "lokasi",
    "label": "Lokasi Tanah",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Tanah",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.9",
    "field_name": "luas",
    "label": "Luas (m2)",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Tanah",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.9",
    "field_name": "no_persil",
    "label": "Nomor Persil",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Tanah",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.9",
    "field_name": "bukti_kepemilikan",
    "label": "Bukti Kepemilikan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Tanah",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.9",
    "field_name": "no_bidang",
    "label": "Nomor Bidang",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Tanah",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "30.9",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "474.4",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 10,
    "help_text": null
  },
  {
    "kode_surat": "474.5",
    "field_name": "anggota_keluarga",
    "label": "Daftar Anggota Keluarga",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keluarga",
    "urutan": 10,
    "help_text": "Nama - NIK - Hubungan"
  },
  {
    "kode_surat": "440.0",
    "field_name": "no_bpjs_lama",
    "label": "No. BPJS Lama (jika ada)",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "BPJS",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "440.0",
    "field_name": "kategori_peserta",
    "label": "Kategori Peserta",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "BPJS",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "440.0",
    "field_name": "anggota_daftar",
    "label": "Anggota yang Didaftarkan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "BPJS",
    "urutan": 10,
    "help_text": "Nama - NIK)"
  },
  {
    "kode_surat": "440.0",
    "field_name": "faskes",
    "label": "Faskes Tujuan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "BPJS",
    "urutan": 11,
    "help_text": null
  },
  {
    "kode_surat": "523.0",
    "field_name": "jenis_nelayan",
    "label": "Jenis Nelayan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Nelayan",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "523.0",
    "field_name": "alat_tangkap",
    "label": "Alat Tangkap",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Nelayan",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "523.0",
    "field_name": "jenis_ukuran_kapal",
    "label": "Jenis/Ukuran Kapal",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Nelayan",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "523.0",
    "field_name": "no_registrasi",
    "label": "No. Registrasi Kapal",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Nelayan",
    "urutan": 12,
    "help_text": null
  },
  {
    "kode_surat": "520.0",
    "field_name": "komoditas_utama",
    "label": "Komoditas Utama",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Petani",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "520.0",
    "field_name": "luas_lahan",
    "label": "Luas Lahan (m2)",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Petani",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "520.0",
    "field_name": "status_kepemilikan",
    "label": "Status Kepemilikan Lahan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Petani",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "520.0",
    "field_name": "lokasi_blok",
    "label": "Lokasi/Blok",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Petani",
    "urutan": 11,
    "help_text": null
  },
  {
    "kode_surat": "461.0",
    "field_name": "jenis_disabilitas",
    "label": "Jenis Disabilitas",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Disabilitas",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "461.0",
    "field_name": "tingkat",
    "label": "Tingkat Disabilitas",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Disabilitas",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "461.0",
    "field_name": "penyebab",
    "label": "Penyebab",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": false,
    "grup": "Disabilitas",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "461.0",
    "field_name": "alat_bantu",
    "label": "Alat Bantu yang Digunakan",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Disabilitas",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "461.0",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Disabilitas",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "610.0",
    "field_name": "nama_ruas",
    "label": "Nama Ruas Jalan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Jalan",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "610.0",
    "field_name": "lokasi",
    "label": "Lokasi/Rute",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Jalan",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "610.0",
    "field_name": "panjang_rusak",
    "label": "Panjang Rusak (m)",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Jalan",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "610.0",
    "field_name": "lebar",
    "label": "Lebar (m)",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Jalan",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "610.0",
    "field_name": "kondisi",
    "label": "Kondisi",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Jalan",
    "urutan": 13,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "610.0",
    "field_name": "status_jalan",
    "label": "Status Jalan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Jalan",
    "urutan": 14,
    "help_text": null
  },
  {
    "kode_surat": "420.0",
    "field_name": "jenjang",
    "label": "Jenjang Pendidikan",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Pendidikan",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "420.0",
    "field_name": "nama_sekolah",
    "label": "Nama Sekolah/Kampus",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pendidikan",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "420.0",
    "field_name": "prodi",
    "label": "Program Studi/Jurusan",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Pendidikan",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "420.0",
    "field_name": "prestasiscore",
    "label": "Prestasi/IPK Terakhir",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Pendidikan",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "420.0",
    "field_name": "keperluan",
    "label": "Keperluan Beasiswa",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Pendidikan",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "474.10",
    "field_name": "jenis_dokumen",
    "label": "Jenis Dokumen",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Dokumen",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.10",
    "field_name": "alasan",
    "label": "Alasan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Dokumen",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.10",
    "field_name": "kantor_tujuan",
    "label": "Kantor Dukcapil Tujuan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Dokumen",
    "urutan": 11,
    "help_text": null
  },
  {
    "kode_surat": "474.12",
    "field_name": "jenis_sptjm",
    "label": "Jenis SPTJM",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "SPTJM",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.12",
    "field_name": "isi_pernyataan",
    "label": "Isi Pernyataan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "SPTJM",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.12",
    "field_name": "saksi1",
    "label": "Saksi 1 - Nama & NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "SPTJM",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.12",
    "field_name": "saksi2",
    "label": "Saksi 2 - Nama & NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "SPTJM",
    "urutan": 21,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.12",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "SPTJM",
    "urutan": 30,
    "help_text": null
  },
  {
    "kode_surat": "474.13",
    "field_name": "agama_asal",
    "label": "Agama Asal",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Agama",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.13",
    "field_name": "agama_sekarang",
    "label": "Agama Sekarang",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Agama",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.13",
    "field_name": "keterangan",
    "label": "Keterangan Perpindahan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Agama",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.13",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Agama",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "477.5",
    "field_name": "nama_anak",
    "label": "Nama Anak",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Akta",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.5",
    "field_name": "ttl_anak",
    "label": "TTL",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Akta",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.5",
    "field_name": "jk",
    "label": "Jenis Kelamin",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Akta",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.5",
    "field_name": "anak_ke",
    "label": "Anak ke-",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Akta",
    "urutan": 4,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.5",
    "field_name": "nik_ayah",
    "label": "NIK Ayah",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Akta",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.5",
    "field_name": "nik_ibu",
    "label": "NIK Ibu",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Akta",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.5",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Akta",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "474.14",
    "field_name": "posisi",
    "label": "Posisi/Perusahaan Dilamar",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Kerja",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.14",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Kerja",
    "urutan": 10,
    "help_text": null
  },
  {
    "kode_surat": "465.0",
    "field_name": "keperluan",
    "label": "Keperluan / Tujuan Permohonan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "alamat_domisili",
    "label": "Alamat Domisili Lengkap",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Domisili",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "dusun",
    "label": "Dusun",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Domisili",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "rt_rw",
    "label": "RT / RW",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Domisili",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "pekerjaan",
    "label": "Pekerjaan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Ekonomi",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "penghasilan",
    "label": "Penghasilan per Bulan (Rp)",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Ekonomi",
    "urutan": 21,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "jumlah_tanggungan",
    "label": "Jumlah Tanggungan",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Keluarga",
    "urutan": 22,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "status_rumah",
    "label": "Status Kepemilikan Rumah",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Ekonomi",
    "urutan": 23,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "465.0",
    "field_name": "no_kk",
    "label": "No. Kartu Keluarga",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Keluarga",
    "urutan": 30,
    "help_text": null
  },
  {
    "kode_surat": "474.6",
    "field_name": "jenis_hilang",
    "label": "Jenis Dokumen/Benda yang Hilang",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "nama_barang",
    "label": "Nama/Merk Barang",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "tanggal_hilang",
    "label": "Tanggal Hilang",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "tempat_hilang",
    "label": "Tempat Hilang",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "penjelasan",
    "label": "Penjelasan Kejadian",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Kehilangan",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.6",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "474.7",
    "field_name": "ttl",
    "label": "Tempat & Tanggal Lahir",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Identitas",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "nik",
    "label": "NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Identitas",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "alamat",
    "label": "Alamat Lengkap",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Alamat",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.7",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "474.8",
    "field_name": "nama_warga",
    "label": "Nama Lengkap",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Identitas",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.8",
    "field_name": "nik_warga",
    "label": "NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Identitas",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.8",
    "field_name": "hubungan",
    "label": "Hubungan dengan yang Dipohonkan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Keluarga",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.8",
    "field_name": "nama_yang_dipohon",
    "label": "Nama yang Dipohonkan",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Keluarga",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "474.8",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "475.0",
    "field_name": "alamat_asal",
    "label": "Alamat Asal",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Asal",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "alamat_tujuan",
    "label": "Alamat Tujuan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Tujuan",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "alasan",
    "label": "Alasan Pindah",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Alasan",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "jumlah_anggota",
    "label": "Jumlah Anggota Keluarga yang Ikut",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Keluarga",
    "urutan": 30,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "475.0",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 40,
    "help_text": null
  },
  {
    "kode_surat": "477.3",
    "field_name": "nama_bayi",
    "label": "Nama Bayi",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Bayi",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.3",
    "field_name": "jenis_kelamin",
    "label": "Jenis Kelamin",
    "tipe": "select",
    "placeholder": "",
    "wajib": true,
    "grup": "Bayi",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.3",
    "field_name": "ttl",
    "label": "Tempat & Tanggal Lahir",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Bayi",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.3",
    "field_name": "nama_ayah",
    "label": "Nama Ayah",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.3",
    "field_name": "nik_ayah",
    "label": "NIK Ayah",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.3",
    "field_name": "nama_ibu",
    "label": "Nama Ibu",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.3",
    "field_name": "nik_ibu",
    "label": "NIK Ibu",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Orang Tua",
    "urutan": 13,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.3",
    "field_name": "alamat",
    "label": "Alamat Keluarga",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Alamat",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "477.4",
    "field_name": "nama_meninggal",
    "label": "Nama Lengkap yang Meninggal",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Meninggal",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "nik_meninggal",
    "label": "NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Meninggal",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "ttl",
    "label": "Tempat & Tanggal Lahir",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Meninggal",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "tanggal_wafat",
    "label": "Tanggal Wafat",
    "tipe": "date",
    "placeholder": "",
    "wajib": true,
    "grup": "Meninggal",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "tempat_wafat",
    "label": "Tempat Wafat",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Meninggal",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "penyebab",
    "label": "Penyebab Kematian",
    "tipe": "text",
    "placeholder": "",
    "wajib": false,
    "grup": "Meninggal",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "nama_pelapor",
    "label": "Nama Pelapor",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pelapor",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "nik_pelapor",
    "label": "NIK Pelapor",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pelapor",
    "urutan": 21,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "477.4",
    "field_name": "hubungan",
    "label": "Hubungan dengan yang Meninggal",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Pelapor",
    "urutan": 22,
    "help_text": null
  },
  {
    "kode_surat": "510.0",
    "field_name": "nama_usaha",
    "label": "Nama Usaha",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "510.0",
    "field_name": "jenis_usaha",
    "label": "Jenis/Bidang Usaha",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "510.0",
    "field_name": "alamat_usaha",
    "label": "Alamat Tempat Usaha",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "510.0",
    "field_name": "modal",
    "label": "Perkiraan Modal (Rp)",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Ekonomi",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "510.0",
    "field_name": "omset",
    "label": "Perkiraan Omset/Bulan (Rp)",
    "tipe": "number",
    "placeholder": "",
    "wajib": false,
    "grup": "Ekonomi",
    "urutan": 21,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "510.0",
    "field_name": "tenaga_kerja",
    "label": "Jumlah Tenaga Kerja",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Ekonomi",
    "urutan": 22,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "510.0",
    "field_name": "tahun_mulai",
    "label": "Tahun Mulai Usaha",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Usaha",
    "urutan": 30,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "510.0",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 40,
    "help_text": null
  },
  {
    "kode_surat": "140.1",
    "field_name": "tujuan",
    "label": "Tujuan / Instansi",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Tujuan",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.1",
    "field_name": "nama",
    "label": "Nama Lengkap",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Identitas",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.1",
    "field_name": "nik",
    "label": "NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Identitas",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.1",
    "field_name": "alamat",
    "label": "Alamat Lengkap",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Alamat",
    "urutan": 12,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "140.1",
    "field_name": "keperluan",
    "label": "Uraian Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "451.1",
    "field_name": "nama_calon",
    "label": "Nama Lengkap",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.1",
    "field_name": "ttl_calon",
    "label": "Tempat & Tanggal Lahir",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.1",
    "field_name": "nik_calon",
    "label": "NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.1",
    "field_name": "alamat_calon",
    "label": "Alamat",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.1",
    "field_name": "alasan",
    "label": "Alasan Dispensasi",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Alasan",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.1",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 30,
    "help_text": null
  },
  {
    "kode_surat": "451.2",
    "field_name": "nama_calon",
    "label": "Nama Lengkap",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.2",
    "field_name": "ttl_calon",
    "label": "Tempat & Tanggal Lahir",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.2",
    "field_name": "nik_calon",
    "label": "NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.2",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 20,
    "help_text": null
  },
  {
    "kode_surat": "451.3",
    "field_name": "nama_wakif",
    "label": "Nama Wakif (yang mewakafkan)",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Wakif",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.3",
    "field_name": "nik_wakif",
    "label": "NIK Wakif",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Wakif",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.3",
    "field_name": "alamat_wakif",
    "label": "Alamat Wakif",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Wakif",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.3",
    "field_name": "lokasi_tanah",
    "label": "Lokasi Tanah yang Diwakafkan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Tanah",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.3",
    "field_name": "luas_tanah",
    "label": "Luas (m2)",
    "tipe": "number",
    "placeholder": "",
    "wajib": true,
    "grup": "Tanah",
    "urutan": 11,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.3",
    "field_name": "nama_mauquf",
    "label": "Nama Mauquf Alaih (penerima)",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Mauquf",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.3",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 30,
    "help_text": null
  },
  {
    "kode_surat": "451.4",
    "field_name": "nama_calon",
    "label": "Nama Lengkap",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 1,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.4",
    "field_name": "ttl_calon",
    "label": "Tempat & Tanggal Lahir",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 2,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.4",
    "field_name": "nik_calon",
    "label": "NIK",
    "tipe": "text",
    "placeholder": "",
    "wajib": true,
    "grup": "Calon",
    "urutan": 3,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.4",
    "field_name": "alamat_asal",
    "label": "Alamat Asal",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Asal",
    "urutan": 10,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.4",
    "field_name": "alamat_num",
    "label": "Alamat Numpang",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Num",
    "urutan": 20,
    "help_text": "NULL)"
  },
  {
    "kode_surat": "451.4",
    "field_name": "keperluan",
    "label": "Keperluan",
    "tipe": "textarea",
    "placeholder": "",
    "wajib": true,
    "grup": "Keperluan",
    "urutan": 30,
    "help_text": null
  }
];

async function run() {
    const { data: jenisAll, error: e1 } = await supabase.from('surat_jenis').select('id, kode_surat, tenant_id');
    if (!jenisAll) return console.error(e1);
    
    const jenisMap = {};
    for (const j of jenisAll) jenisMap[j.kode_surat] = j;

    const payload = [];
    const seen = new Set();
    for (const d of missingDnas) {
        if (!jenisMap[d.kode_surat]) continue;
        const key = d.kode_surat + '_' + d.field_name;
        if (seen.has(key)) continue;
        seen.add(key);
        
        payload.push({
            tenant_id: jenisMap[d.kode_surat].tenant_id,
            jenis_surat_id: jenisMap[d.kode_surat].id,
            ...d
        });
    }

    console.log(`Inserting ${payload.length} missing DNA fields...`);
    const { error } = await supabase.from('surat_jenis_dna').upsert(payload, { onConflict: 'jenis_surat_id,field_name' });
    if (error) console.error(error);
    else console.log("Done successfully!");
}
run();
