-- ============================================
-- PENDUDUK (matches current schema)
-- ============================================

DO $$
DECLARE
  v_tenant_id UUID;
BEGIN
  SELECT id INTO v_tenant_id FROM public.tenants LIMIT 1;

  INSERT INTO public.penduduk (
    tenant_id, nik, nama, jenis_kelamin, tempat_lahir, tanggal_lahir,
    agama, pendidikan, pekerjaan, status_kawin, hubungan_kk,
    keluarga_id, dusun, alamat,
    foto_url, status_hidup, catatan,
    created_at, updated_at,
    bpjs_status, bpjs_nomor,
    rt, rw, nomor_hp,
    created_by, updated_by
  )
  SELECT
    v_tenant_id,
    nik, nama, jenis_kelamin, tempat_lahir, tanggal_lahir,
    agama, pendidikan, pekerjaan, status_kawin, hubungan_kk,
    NULL,
    dusun, alamat,
    NULL, 'hidup', NULL,
    NOW(), NOW(),
    NULL, NULL,
    rt, NULL, NULL,
    NULL, NULL
  FROM (
    SELECT '7310012507780003' AS nik,
  'JAMALUDDIN' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'PL MAKARANGANAN' AS status_kawin,
  '' AS hubungan_kk,
  '5203082809180013' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 5.0' AS alamat
  UNION ALL
  SELECT '5203080603850006' AS nik,
  'HERMAN' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'LB. LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203082810130043' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 5.0' AS alamat
  UNION ALL
  SELECT '5203080608640002' AS nik,
  'AMAQ MUSA' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'KP. SASAK' AS status_kawin,
  '' AS hubungan_kk,
  '5203082903120017' AS no_kk_ref,
  'Mumbul Utara' AS dusun,
  'Mumbul Utara RT 2.0' AS alamat
  UNION ALL
  SELECT '5203087112770276' AS nik,
  'MUKMINAH' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203082904200010' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 5.0' AS alamat
  UNION ALL
  SELECT '5203085206020005' AS nik,
  'INDAH SARI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203082911110017' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 1.0' AS alamat
  UNION ALL
  SELECT '5203087112680364' AS nik,
  'INAQ MAHYUDIN' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LB. LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203082911120012' AS no_kk_ref,
  'Seruni Timur' AS dusun,
  'Seruni Timur RT 1.0' AS alamat
  UNION ALL
  SELECT '5203084502700003' AS nik,
  'HAESUM' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LB. LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203082911120023' AS no_kk_ref,
  'Seruni Timur' AS dusun,
  'Seruni Timur RT 1.0' AS alamat
  UNION ALL
  SELECT '5203081707750001' AS nik,
  'MUSTAFA' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'PANCOR' AS status_kawin,
  '' AS hubungan_kk,
  '5203083001100039' AS no_kk_ref,
  'Mumbul Utara' AS dusun,
  'Mumbul Utara RT 1.0' AS alamat
  UNION ALL
  SELECT '5203083011030002' AS nik,
  'MARJAN' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083003210006' AS no_kk_ref,
  'Seruni Timur' AS dusun,
  'Seruni Timur RT 1.0' AS alamat
  UNION ALL
  SELECT '5203087112580150' AS nik,
  'PATIMAH' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'BANDOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083004180008' AS no_kk_ref,
  'Mumbul Selatan' AS dusun,
  'Mumbul Selatan RT 1.0' AS alamat
  UNION ALL
  SELECT '5203087112820494' AS nik,
  'SUMIATI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'TANJUNG TEROS' AS status_kawin,
  '' AS hubungan_kk,
  '5203083009130011' AS no_kk_ref,
  'Seruni Timur' AS dusun,
  'Seruni Timur RT 1.0' AS alamat
  UNION ALL
  SELECT '5203080404900010' AS nik,
  'ANDI RUSLI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083009140010' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 4.0' AS alamat
  UNION ALL
  SELECT '5203087112750640' AS nik,
  'SARIMAH' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LB. LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083009140014' AS no_kk_ref,
  'Mumbul Utara' AS dusun,
  'Mumbul Utara RT 5.0' AS alamat
  UNION ALL
  SELECT '5203084109900005' AS nik,
  'PATMAWATI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083010120029' AS no_kk_ref,
  'Mumbul Utara' AS dusun,
  'Mumbul Utara RT 3.0' AS alamat
  UNION ALL
  SELECT '5203086002910006' AS nik,
  'SURYATI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083010120106' AS no_kk_ref,
  'Mumbul Utara' AS dusun,
  'Mumbul Utara RT 2.0' AS alamat
  UNION ALL
  SELECT '5203087112760418' AS nik,
  'ROHANI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'SERUNI MUMBUL' AS status_kawin,
  '' AS hubungan_kk,
  '5203083012140013' AS no_kk_ref,
  'Mumbul Utara' AS dusun,
  'Mumbul Utara RT 5.0' AS alamat
  UNION ALL
  SELECT '5205075102920001' AS nik,
  'SUHARNI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'SORI UTU' AS status_kawin,
  '' AS hubungan_kk,
  '5203083012140015' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 3.0' AS alamat
  UNION ALL
  SELECT '5203085008030009' AS nik,
  'RARANTI SARA' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083103150019' AS no_kk_ref,
  'Mumbul Utara' AS dusun,
  'Mumbul Utara RT 4.0' AS alamat
  UNION ALL
  SELECT '5203087112970127' AS nik,
  'KAMARIAH' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083110120079' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 1.0' AS alamat
  UNION ALL
  SELECT '5203081012990008' AS nik,
  'TAUFIK' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083110120079' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 1.0' AS alamat
  UNION ALL
  SELECT '5203086112650003' AS nik,
  'HALIMAH' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'LABUHAN LOMBOK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083110120079' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 1.0' AS alamat
  UNION ALL
  SELECT '5203081011600003' AS nik,
  'NAWAWI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'JANTUK' AS status_kawin,
  '' AS hubungan_kk,
  '5203083110120079' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 1.0' AS alamat
  UNION ALL
  SELECT '5203170405180005' AS nik,
  'ARDIAN DIWANESA' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'SERUNI MUMBUL' AS status_kawin,
  '' AS hubungan_kk,
  '5203170306200005' AS no_kk_ref,
  'Mumbul Selatan' AS dusun,
  'Mumbul Selatan RT 4.0' AS alamat
  UNION ALL
  SELECT '6473031302100002' AS nik,
  'MUHAMMAD ALFAHRI' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'TARAKAN' AS status_kawin,
  '' AS hubungan_kk,
  '6473021009140001' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 2.0' AS alamat
  UNION ALL
  SELECT '6473031509850006' AS nik,
  'ARIFIN' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '1' AS pendidikan,
  'L' AS pekerjaan,
  'TOLI-TOLI' AS status_kawin,
  '' AS hubungan_kk,
  '6473021009140001' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 2.0' AS alamat
  UNION ALL
  SELECT '7310016103730001' AS nik,
  'IRAKIBA' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'PL MAKARANGANAN' AS status_kawin,
  '' AS hubungan_kk,
  '7310011707070004' AS no_kk_ref,
  'Seruni Barat' AS dusun,
  'Seruni Barat RT 4.0' AS alamat
  UNION ALL
  SELECT '7310014708020001' AS nik,
  'NUR FADILLAH' AS nama,
  'LOMBOK TIMUR' AS jenis_kelamin,
  'SERUNI MUMBUL' AS tempat_lahir,
  NULL::date AS tanggal_lahir,
  'NUSA TENGGARA BARAT' AS agama,
  '2' AS pendidikan,
  'P' AS pekerjaan,
  'PULAU TAMPAANG' AS status_kawin,
  '' AS hubungan_kk,
  '7310012805080010' AS no_kk_ref,
  'Mumbul Selatan' AS dusun,
  'Mumbul Selatan RT 1.0' AS alamat
  ) AS t(
    nik, nama, jenis_kelamin, tempat_lahir, tanggal_lahir,
    agama, pendidikan, pekerjaan, status_kawin, hubungan_kk,
    no_kk_ref, dusun, alamat
  )
  WHERE nik NOT IN (SELECT nik FROM public.penduduk WHERE nik IS NOT NULL);
END $$;
